# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

FROM alpine:3.21
RUN apk add --no-cache jq curl bash
ENTRYPOINT ["/bin/bash"]