{
 "title": "JVM Executor Services",
 "tags": [
  "jvm",
  "executors",
  "pools"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(daml_executor_pool_size, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(daml_executor_pool_size{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(daml_executor_pool_size{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   },
   {
    "name": "name",
    "query": "label_values(daml_executor_pool_size{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}, name)"
   },
   {
    "name": "group_without",
    "query": "endpoint, instance,daml_version,job,namespace,container,canton_version"
   }
  ]
 },
 "panels": [
  {
   "title": "Runtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Run Latency (p95)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, namespace, pod, container, name, component, participant) (rate(daml_executor_runtime_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}[$__rate_interval])))",
       "legendFormat": "{{pod}} - {{container}} - {{name}} / {{component}} {{participant}}"
      }
     ]
    },
    {
     "title": "Task Run Latency (average)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum without() (daml_executor_runtime_duration_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}) / sum without() (daml_executor_runtime_duration_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"})",
       "legendFormat": "{{pod}} - {{container}} - {{name}} / {{component}} {{participant}}"
      }
     ]
    },
    {
     "title": "Task Idle Duration (p95)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, namespace, pod, container, name, component, participant) (rate(daml_executor_runtime_idle_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}[$__rate_interval])))",
       "legendFormat": "{{pod}} - {{container}} - {{name}} / {{component}} {{participant}}"
      }
     ]
    },
    {
     "title": "Task Idle Duration (average)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum without() (daml_executor_runtime_idle_duration_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}) / sum without() (daml_executor_runtime_idle_duration_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"})",
       "legendFormat": "{{pod}} - {{container}} - {{name}}"
      }
     ]
    },
    {
     "title": "Submitted Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without($group_without) (rate(daml_executor_runtime_submitted_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} - {{container}} - {{name}}"
      }
     ]
    },
    {
     "title": "Completed Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without($group_without) (rate(daml_executor_runtime_completed_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} - {{container}} - {{name}}"
      }
     ]
    },
    {
     "title": "Running Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without($group_without) (daml_executor_runtime_running{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"})",
       "legendFormat": "{{pod}} - {{container}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Common Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Size",
     "type": "timeseries",
     "description": "Common between thread and fork-join pools",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "daml_executor_pool_size{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}",
       "legendFormat": "{{pod}} - {{container}} - {{name}} / {{type}}"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "timeseries",
     "description": "Common between thread and fork-join pools",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "daml_executor_threads_active{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}",
       "legendFormat": "{{pod}} - {{container}} - {{name}} / {{type}}"
      }
     ]
    },
    {
     "title": "Queued Tasks",
     "type": "timeseries",
     "description": "Common between thread and fork-join pools",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "daml_executor_tasks_queued{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}",
       "legendFormat": "{{pod}} - {{container}} - {{name}} / {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fork-Join Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "daml_executor_threads_running{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}",
       "legendFormat": "{{pod}} - {{container}} - {{name}}"
      }
     ]
    },
    {
     "title": "Stolen Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without($group_without) (rate(daml_executor_tasks_stolen{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} - {{container}} - {{name}}"
      }
     ]
    },
    {
     "title": "Task Queuing Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without($group_without) (rate(daml_executor_tasks_executing_queued{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} - {{container}} - {{name}}"
      }
     ]
    },
    {
     "title": "Queued Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "daml_executor_tasks_executing_queued{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", name=\"$name\"}",
       "legendFormat": "{{pod}} - {{container}} - {{name}}"
      }
     ]
    }
   ]
  }
 ]
}