# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

ARG JAVA_VERSION=0
FROM eclipse-temurin:${JAVA_VERSION}
RUN apt-get update && apt-get install -y jq curl bash

